#!/usr/bin/env python3
"""
MOOS-IvP Mission Builder Backend
Provides coordinate conversion and MOOS file generation services
"""

import math
import json
from typing import List, Dict, Tuple
import argparse
import sys

class CoordinateConverter:
    """Convert between latitude/longitude and local MOOS coordinates"""
    
    def __init__(self, lat_origin: float, lon_origin: float):
        self.lat_origin = lat_origin
        self.lon_origin = lon_origin
        
    def to_local(self, lat: float, lon: float) -> Tuple[float, float]:
        """Convert lat/lon to local x,y coordinates"""
        # Simple approximation - in production would use proper UTM conversion
        x = (lon - self.lon_origin) * 111320 * math.cos(math.radians(lat))
        y = (lat - self.lat_origin) * 110540
        return x, y
        
    def to_global(self, x: float, y: float) -> Tuple[float, float]:
        """Convert local x,y to lat/lon coordinates"""
        lat = self.lat_origin + (y / 110540)
        lon = self.lon_origin + (x / (111320 * math.cos(math.radians(lat))))
        return lat, lon

class MissionGenerator:
    """Generate MOOS configuration files from mission parameters"""
    
    def __init__(self):
        self.waypoints = []
        self.behaviors = []
        self.config = {}
        
    def add_waypoint(self, lat: float, lon: float, name: str = ""):
        """Add a waypoint to the mission"""
        wp = {
            'lat': lat,
            'lon': lon,
            'name': name or f"WP{len(self.waypoints) + 1}"
        }
        self.waypoints.append(wp)
        
    def add_behavior(self, behavior_type: str, name: str, params: Dict):
        """Add a behavior to the mission"""
        bhv = {
            'type': behavior_type,
            'name': name,
            'params': params
        }
        self.behaviors.append(bhv)
        
    def set_config(self, config: Dict):
        """Set mission configuration parameters"""
        self.config.update(config)
        
    def generate_moos_file(self, output_file: str = None) -> str:
        """Generate the .moos configuration file"""
        
        # Default configuration
        default_config = {
            'mission_name': 'auto_mission',
            'community': 'alpha',
            'time_warp': 1,
            'lat_origin': 43.825300,
            'lon_origin': -70.330400,
            'vehicle_type': 'kayak',
            'server_host': 'localhost',
            'server_port': 9000
        }
        
        config = {**default_config, **self.config}
        
        moos_content = f"""//------------------------------------------------------------------------
// MOOS Configuration File - Generated by MOOS-IvP Mission Builder
// Mission: {config['mission_name']}
// Community: {config['community']}
//------------------------------------------------------------------------

ServerHost   = {config['server_host']}
ServerPort   = {config['server_port']}
Community    = {config['community']}
MOOSTimeWarp = {config['time_warp']}

// Coordinate Origin
LatOrigin  = {config['lat_origin']}
LongOrigin = {config['lon_origin']}

//------------------------------------------
// Antler configuration block
ProcessConfig = ANTLER
{{
  MSBetweenLaunches = 200

  Run = MOOSDB          @ NewConsole = false
  Run = pLogger         @ NewConsole = false
  Run = uSimMarineV23   @ NewConsole = false
  Run = pMarinePIDV22   @ NewConsole = false
  Run = pHelmIvP        @ NewConsole = false
  Run = pMarineViewer   @ NewConsole = false
  Run = pNodeReporter   @ NewConsole = false
  Run = uProcessWatch   @ NewConsole = false
  Run = pRealm          @ NewConsole = false
}}

//------------------------------------------
// uSimMarineV23 config block
ProcessConfig = uSimMarineV23
{{
  AppTick   = 10
  CommsTick = 10

  START_POS = 0,0,180,0
  PREFIX    = NAV

  TURN_RATE = 40
  THRUST_MAP = 0:0, 20:1, 40:2, 60:3, 80:4, 100:5
  THRUST_REFLECT = true
}}

//------------------------------------------
// pHelmIvP config block
ProcessConfig = pHelmIvP
{{
  AppTick    = 4
  CommsTick  = 4

  Behaviors    = {config['mission_name']}.bhv
  Verbose      = false
  Domain       = course:0:359:360
  Domain       = speed:0:5:26
}}

//------------------------------------------
// pMarinePIDV22 config block
ProcessConfig = pMarinePIDV22
{{
  AppTick    = 10
  CommsTick  = 10

  VERBOSE       = true
  DEPTH_CONTROL = false
  ACTIVE_START  = true

  // Yaw PID controller
  YAW_PID_KP             = 0.9
  YAW_PID_KD             = 0.3
  YAW_PID_KI             = 0.3
  YAW_PID_INTEGRAL_LIMIT = 0.07

  // Speed PID controller
  SPEED_PID_KP           = 1.0
  SPEED_PID_KD           = 0.0
  SPEED_PID_KI           = 0.0
  SPEED_PID_INTEGRAL_LIMIT = 0.07

  MAXRUDDER    = 100
  MAXTHRUST    = 100

  SPEED_FACTOR = 20
}}

//------------------------------------------
// pMarineViewer config block
ProcessConfig = pMarineViewer
{{
  AppTick    = 4
  CommsTick  = 4

  TIFF_FILE            = forrest19.tif
  set_pan_x            = -90
  set_pan_y            = -280
  zoom                 = 0.65
  vehicles_shape_scale = 1.5
  vehicles_name_mode   = names

  point_viewable_all = true
  polygon_viewable_all = true
  seglist_viewable_all = true
  
  SCOPE = HELM_STATE
  SCOPE = DEPLOY
  SCOPE = RETURN
  SCOPE = WPT_STAT
  SCOPE = VIEW_SEGLIST
  SCOPE = VIEW_POINT
  SCOPE = VIEW_POLYGON
  SCOPE = MVIEWER_LCLICK
  SCOPE = MVIEWER_RCLICK

  BUTTON_ONE = DEPLOY # DEPLOY=true
  BUTTON_ONE = MOOS_MANUAL_OVERRIDE=false # RETURN=false
  BUTTON_TWO = RETURN # RETURN=true

  ACTION = MENU_KEY=deploy # DEPLOY = true # RETURN = false
  ACTION = MENU_KEY=return # RETURN = true
}}

//------------------------------------------
// pLogger config block
ProcessConfig = pLogger
{{
  AppTick       = 10
  CommsTick     = 10

  File          = {config['mission_name']}
  PATH          = ./
  SyncLog       = true @ 0.2
  AsyncLog      = true
  FileTimeStamp = true

  LogAuxSrc     = true

  WildCardLogging = true
  WildCardOmitPattern = *_STATUS
  WildCardOmitPattern = DB_VARSUMMARY
  WildCardOmitPattern = DB_RWSUMMARY
}}

//------------------------------------------
// pNodeReporter config block
ProcessConfig = pNodeReporter
{{
  AppTick     = 2
  CommsTick   = 2

  VESSEL_TYPE = {config['vehicle_type']}
}}

//------------------------------------------
// uProcessWatch config block
ProcessConfig = uProcessWatch
{{
  AppTick   = 1
  CommsTick   = 1

  ALLOW_RETRACTIONS = true

  WATCH_ALL = true
  NOWATCH = uXMS*
  NOWATCH = uPokeDB*

  SUMMARY_WAIT = 12
}}

//------------------------------------------
// pRealm config block
ProcessConfig = pRealm
{{
  AppTick   = 4
  CommsTick   = 4

  RELCAST_INTERVAL = 0.5
  SUMMARY_INTERVAL = 2.0

  HIST_VAR = HELM_STATE
  HIST_VAR = DEPLOY
  HIST_VAR = RETURN
}}"""

        if output_file:
            with open(output_file, 'w') as f:
                f.write(moos_content)
                
        return moos_content
        
    def generate_behavior_file(self, output_file: str = None) -> str:
        """Generate the .bhv behavior file"""
        
        config = self.config
        mission_name = config.get('mission_name', 'auto_mission')
        cruise_speed = config.get('cruise_speed', 3.0)
        capture_radius = config.get('capture_radius', 5.0)
        
        bhv_content = f"""//------------------------------------------------------------------------
// Behavior File - Generated by MOOS-IvP Mission Builder
// Mission: {mission_name}
//------------------------------------------------------------------------

initialize   DEPLOY = false
initialize   RETURN = false"""

        # Add waypoint behavior if waypoints exist
        if self.waypoints:
            converter = CoordinateConverter(
                config.get('lat_origin', 43.825300),
                config.get('lon_origin', -70.330400)
            )
            
            # Convert waypoints to local coordinates
            local_waypoints = []
            for wp in self.waypoints:
                x, y = converter.to_local(wp['lat'], wp['lon'])
                local_waypoints.append(f"{x:.1f},{y:.1f}")
            
            waypoint_str = ":".join(local_waypoints)
            
            bhv_content += f"""

//----------------------------------------------
Behavior = BHV_Waypoint
{{ 
  name      = waypt_survey
  pwt       = 100
  condition = RETURN = false
  condition = DEPLOY = true
  endflag   = RETURN = true

  updates    = WPT_UPDATE
  perpetual  = true

  speed = {cruise_speed}   // meters per second
  capture_radius = {capture_radius}
  slip_radius = {capture_radius * 3}
  
  efficiency_measure = all
  polygon = {waypoint_str}
  order = normal
  repeat = 0

  visual_hints = nextpt_color=yellow
  visual_hints = nextpt_vertex_size=8
  visual_hints = trails_color=khaki
  visual_hints = trails_length=300
}}"""

        # Add station keeping behavior
        bhv_content += f"""

//----------------------------------------------
Behavior = BHV_StationKeep
{{
  name      = station-keep
  pwt       = 100
  condition = DEPLOY = true
  condition = RETURN = true

  center_activate = true
  inner_radius = 5
  outer_radius = 10 
  outer_speed = 1.0

  transit_speed = 1.3
  swing_time = 7
  visual_hints = vertex_size=0, edge_color=gray
}}"""

        # Add custom behaviors
        for behavior in self.behaviors:
            if behavior['type'] == 'loiter':
                bhv_content += self._generate_loiter_behavior(behavior)
            elif behavior['type'] == 'constant_heading':
                bhv_content += self._generate_constant_heading_behavior(behavior)
                
        if output_file:
            with open(output_file, 'w') as f:
                f.write(bhv_content)
                
        return bhv_content
        
    def _generate_loiter_behavior(self, behavior: Dict) -> str:
        """Generate a loiter behavior block"""
        params = behavior['params']
        
        return f"""

//----------------------------------------------
Behavior = BHV_Loiter
{{
  name      = {behavior['name']}
  pwt       = {params.get('priority', 100)}
  condition = {params.get('condition', 'DEPLOY = true')}

  updates   = UP_LOITER
  duration  = {params.get('duration', 'no-time-limit')}
  speed     = {params.get('speed', 2.0)}

  polygon   = {params.get('polygon', 'radial:: x=0,y=0,radius=20,pts=8')}
  
  visual_hints = nextpt_color=white, nextpt_lcolor=khaki
  visual_hints = edge_color=orange, vertex_color=white
  visual_hints = edge_size=1, vertex_size=2
}}"""

    def _generate_constant_heading_behavior(self, behavior: Dict) -> str:
        """Generate a constant heading behavior block"""
        params = behavior['params']
        
        return f"""

//----------------------------------------------
Behavior = BHV_ConstantHeading
{{
  name      = {behavior['name']}
  pwt       = {params.get('priority', 100)}
  condition = {params.get('condition', 'DEPLOY = true')}

  duration  = {params.get('duration', 60)}
  heading   = {params.get('heading', 0)}
  speed     = {params.get('speed', 2.0)}
}}"""

    def load_from_json(self, json_data: str):
        """Load mission from JSON data"""
        data = json.loads(json_data)
        
        self.config = data.get('config', {})
        self.waypoints = data.get('waypoints', [])
        self.behaviors = data.get('behaviors', [])
        
    def save_to_json(self) -> str:
        """Save mission to JSON format"""
        data = {
            'config': self.config,
            'waypoints': self.waypoints,
            'behaviors': self.behaviors
        }
        return json.dumps(data, indent=2)

def main():
    """Command line interface for mission generation"""
    parser = argparse.ArgumentParser(description='MOOS-IvP Mission Builder')
    parser.add_argument('--json', type=str, help='Input JSON mission file')
    parser.add_argument('--output', type=str, help='Output file prefix')
    parser.add_argument('--waypoints', type=str, help='Waypoints as lat,lon;lat,lon;...')
    parser.add_argument('--mission-name', type=str, default='test_mission')
    parser.add_argument('--community', type=str, default='alpha')
    
    args = parser.parse_args()
    
    generator = MissionGenerator()
    
    if args.json:
        with open(args.json, 'r') as f:
            generator.load_from_json(f.read())
    else:
        # Set basic configuration
        generator.set_config({
            'mission_name': args.mission_name,
            'community': args.community
        })
        
        # Parse waypoints if provided
        if args.waypoints:
            for wp_str in args.waypoints.split(';'):
                lat, lon = map(float, wp_str.split(','))
                generator.add_waypoint(lat, lon)
    
    output_prefix = args.output or generator.config.get('mission_name', 'mission')
    
    # Generate files
    moos_file = f"{output_prefix}.moos"
    bhv_file = f"{output_prefix}.bhv"
    
    generator.generate_moos_file(moos_file)
    generator.generate_behavior_file(bhv_file)
    
    print(f"Generated mission files:")
    print(f"  {moos_file}")
    print(f"  {bhv_file}")
    
    # Also save mission as JSON for future editing
    json_file = f"{output_prefix}.json"
    with open(json_file, 'w') as f:
        f.write(generator.save_to_json())
    print(f"  {json_file}")

if __name__ == '__main__':
    main()
